name: Build

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release Please

    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
      major: ${{ steps.release_please.outputs.major }}
      minor: ${{ steps.release_please.outputs.minor }}
      patch: ${{ steps.release_please.outputs.patch }}

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release_please
        with:
          release-type: node
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          pull-request-title-pattern: 'chore${scope}: 🔖 release${component} ${version}'

  build-windows:
    runs-on: windows-latest
    name: Build Windows
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          npm run make

      - name: Upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} ".\out\make\squirrel.windows\x64\BSR Altair App-${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }} Setup.exe"

  build-macos:
    runs-on: macos-12
    name: Build Macos
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          npm run make

      - name: Upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} ./out/make/*
